name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.lb.LandmineBusters
description: LandmineBusters minigame plugin for ${release.lang}
author: ucchy

commands:
  landminebusters:
    description: Commands of LandmineBusters
    aliases: [lb]
    usage: |
           /<command> start [difficulty] - Start new game.
           /<command> cancel - Cancel game.
           /<command> rank [difficulty] [num] - View ranking data.
           /<command> reload - Reload config data.
    permission: LandmineBusters.command
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  LandmineBusters.command:
    description: Permission of command.
    default: true
  LandmineBusters.start:
    description: Permission of start command.
    default: true
  LandmineBusters.rank:
    description: Permission of rank command.
    default: true
  LandmineBusters.reload:
    description: Permission of reload command.
    default: op
  'LandmineBusters.*':
    description: All of permissions.
    children:
      LandmineBusters.command: true
      LandmineBusters.start: true
      LandmineBusters.rank: true
      LandmineBusters.reload: true
